version: "3.8"
services:
  api-gateway:
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    #build: .
    image: in10sdev/demo-api-gateway:2.2
    container_name: "demo-api-gateway"
    ports:
      - 9191:9191
    
  eureka-server:
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    #build: .
    image: in10sdev/demo-eureka-server:2.2
    container_name: "demo-eureka-server"
    ports:
      - 8761:8761 
      
  address-service:
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    #build: .
    image: in10sdev/demo-address-service:2.2
    container_name: "demo-address-service"
    ports:
      - 8082:8082
      
  student-service:
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    #build: .
    image: in10sdev/demo-student-service:2.2
    container_name: "demo-student-service"
    ports:
      - 8081:8081
   
#